# Generated by Django 5.2.7 on 2025-11-06 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(default='Port Harcourt, Nigeria', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('head_office_email', models.EmailField(max_length=254, null=True)),
                ('head_office_phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('support_office_email', models.EmailField(max_length=254, null=True)),
                ('support_office_phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('sales_office_email', models.EmailField(max_length=254, null=True)),
                ('sales_office_phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('purchase_office_email', models.EmailField(max_length=254, null=True)),
                ('purchase_office_phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('linkedIn_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(default='EXPLORE NOW', max_length=50)),
                ('button_link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='homepage/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
