# Generated by Django 5.2.7 on 2025-10-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Port Harcourt, Nigeria', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('linkedIn_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
