# Generated by Django 5.2.7 on 2025-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'PIECE'), ('KG', 'KG'), ('PACK', 'PACK')], default='piece', max_length=50),
        ),
    ]
