# Generated by Django 5.2.7 on 2025-10-13 16:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
